const priestSpells = [
    {
        "spellLevel": 1,
        "spellName": "BLESS / CURSE",
        "reversable": "Y",
        "costOfComponents": "HW / UHW",
        "sphere": "ALL",
        "range": "60YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "6RDS",
        "areaOfEffect": "50' CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "COMBINE",
        "sphere": "ALL",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "CIRCLE OF PRIESTS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "DETECT MAGIC",
        "costOfComponents": "HS",
        "sphere": "ALL",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN",
        "areaOfEffect": "10' X 30YDS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "PURIFY FOOD & DRINK",
        "sphere": "ALL",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1CUFT/LEVEL IN 10SQFT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "ANIMAL FRIENDSHIP",
        "costOfComponents": "HS, FOOD",
        "sphere": "ANIMAL",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1HR",
        "duration": "SPECIAL",
        "areaOfEffect": "1 ANIMAL",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 1,
        "spellName": "DETECT SNARES & PITS",
        "costOfComponents": "HS",
        "sphere": "ANIMAL",
        "range": 0,
        "components": "VSM",
        "castingTime": 4,
        "duration": "1 TURN + 1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "INVISIBILITY TO ANIMALS",
        "costOfComponents": "HOLLY",
        "sphere": "ANIMAL",
        "range": "TOUCH",
        "components": "SM",
        "castingTime": 4,
        "duration": "1 TURN + 1RD / LEVEL",
        "areaOfEffect": "1 CREATURE TOUCHED / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "LOCATE ANIMALS OR PLANTS",
        "costOfComponents": "HS",
        "sphere": "ANIMAL",
        "range": "100YDS +20YDS/LEVEL",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "20FT WIDE PATH 20YDS / LEVEL LONG",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "COMMAND",
        "sphere": "CHARM",
        "range": "30YDS",
        "components": "V",
        "castingTime": 1,
        "duration": "1RD",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "REMOVE FEAR / CAUSE FEAR",
        "reversable": "Y",
        "sphere": "CHARM",
        "range": "10YDS",
        "components": "VS",
        "castingTime": 1,
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE / 4 LEVELS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 1,
        "spellName": "SANTUARY",
        "costOfComponents": "HS & A SM SILVER MIRROR",
        "sphere": "CHARM",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "2RDS + 1RD/LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "COMMAND",
        "sphere": "COMBAT",
        "range": "30YDS",
        "components": "V",
        "castingTime": 1,
        "duration": "1RD",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "MAGICAL STONE",
        "costOfComponents": "HS, 3 PEBBLES",
        "sphere": "COMBAT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "SPECIAL",
        "areaOfEffect": "3 PEBBLES",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "CREATION",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 4,
        "duration": "1HR + 1 TURN / LEVEL",
        "areaOfEffect": "20FT RADIUS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 1,
        "spellName": "DETECT EVIL / DETECT GOOD",
        "reversable": "Y",
        "costOfComponents": "HS",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN + 1 TURN / LEVEL",
        "areaOfEffect": "10FT PATH X 120YDS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "DETECT POISON",
        "costOfComponents": "A STRIP OF BLESSED VELLUM",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VSM",
        "castingTime": 4,
        "duration": "1 TURN + 1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "CREATE WATER / DESTROY WATER",
        "reversable": "Y",
        "costOfComponents": "DROP OF WATER / DUST",
        "sphere": "ELEMENTAL WATER",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "UP TO 27CUFT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "GUARDIAN",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 4,
        "duration": "1HR + 1 TURN / LEVEL",
        "areaOfEffect": "20FT RADIUS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 1,
        "spellName": "CURE LIGHT WOUNDS / CAUSE LIGHT WOUNDS",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 5,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "COMMAND",
        "sphere": "LAW",
        "range": "30YDS",
        "components": "V",
        "castingTime": 1,
        "duration": "1RD",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "INVISIBILITY TO UNDEAD",
        "costOfComponents": "HS",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "6RDS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 1,
        "spellName": "DETECT SNARES & PITS",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "1 MILE RADIUS",
        "components": "VS",
        "castingTime": 7,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "ENTANGLE",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "80YDS",
        "components": "VSM",
        "castingTime": 4,
        "duration": "1 TURN",
        "areaOfEffect": "40FT CUBE",
        "savingsThrow": 1
    },
    {
        "spellLevel": 1,
        "spellName": "LOCATE ANIMALS OR PLANTS",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "100YDS +20YDS/LEVEL",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "20FT WIDE PATH 20YDS / LEVEL LONG",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "PASS WITHOUT TRACE",
        "costOfComponents": "SPRIG OF EVERGREEN BURNED & SCATTERED",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "SHILLELAGH",
        "costOfComponents": "HS & A SHAMROCK LEAF",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 2,
        "duration": "4RDS + 1RD / LEVEL",
        "areaOfEffect": "1 NORMAL OAKEN CLUB",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "ENDURE HEAT/ENDURE COLD",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "11HRS / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "PROTECTION FROM EVIL / GOOD",
        "reversable": "Y",
        "costOfComponents": "HS & INCENSE",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "3RDS / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "SANCTUARY",
        "costOfComponents": "HS & A SM SILVER MIRROR",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "2RDS + 1RD/LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "SUN",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 4,
        "duration": "1HR + 1 TURN / LEVEL",
        "areaOfEffect": "20FT RADIUS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 1,
        "spellName": "KNOW TIME",
        "sphere": "TIME",
        "range": 0,
        "components": "VS",
        "castingTime": 1,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 1,
        "spellName": "FAERIE FIRE",
        "costOfComponents": "SMALL PC OF FOXFIRE",
        "sphere": "WEATHER",
        "range": "80YDS",
        "components": "VSM",
        "castingTime": 4,
        "duration": "4RDS / LEVEL",
        "areaOfEffect": "10SQFT / LEVEL IN A 40FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "CHANT",
        "sphere": "ALL",
        "range": 0,
        "components": "VS",
        "castingTime": "2RDS",
        "duration": "TIME OF CHANTING",
        "areaOfEffect": "30FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "CHARM PERSON OR MAMMAL",
        "sphere": "ANIMAL",
        "range": "80YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "SPECIAL",
        "areaOfEffect": "1 PERSON OR MAMMAL",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "MESSENGER",
        "sphere": "ANIMAL",
        "range": "20YDS / LEVEL",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "SNAKE CHARM",
        "sphere": "ANIMAL",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "SPECIAL",
        "areaOfEffect": "30FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "SPEAK WITH ANIMALS",
        "sphere": "ANIMAL",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 ANIMAL /W 30FT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "DETECT CHARM / UNDETECTABLE CHARM",
        "reversable": "Y",
        "sphere": "CHARM",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 TURN",
        "areaOfEffect": "1 CREATURE / RD",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "ENTHRALL",
        "sphere": "CHARM",
        "range": 0,
        "components": "VS",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "90FT RADIUS",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "HOLD PERSON",
        "costOfComponents": "A SM STRAIGHT PC OF IRON",
        "sphere": "CHARM",
        "range": "120 YDS",
        "components": "VSM",
        "castingTime": 5,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 TO 4 PERSONS IN A 20' CUBE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "MESSENGER",
        "sphere": "CHARM",
        "range": "20YDS / LEVEL",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "SNAKE CHARM",
        "sphere": "CHARM",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "SPECIAL",
        "areaOfEffect": "30FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "AID",
        "costOfComponents": "HS & A STRIP OF WHITE CLOTH /W STICKY SUBSTANCE",
        "sphere": "COMBAT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 5,
        "duration": "1RD + 1RD/LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "SPIRITUAL HAMMER",
        "costOfComponents": "A NORMAL WARHAMMER",
        "sphere": "COMBAT",
        "range": "10YDS / LEVEL",
        "components": "VSM",
        "castingTime": 5,
        "duration": "3RDS + 1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "AUGURY",
        "costOfComponents": "A SET OF GEM INLAID STICKS, DRAGON BONES OR TOKENS OF AT LEAST 1,000GP VALUE",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VSM",
        "castingTime": "2RDS",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "DETECT CHARM / UNDETECTABLE CHARM",
        "reversable": "Y",
        "sphere": "DIVINATION",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 TURN",
        "areaOfEffect": "1 CREATURE / RD",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "FIND TRAPS",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "3 TURNS",
        "areaOfEffect": "10FT X 90FT PATH",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "KNOW ALIGNMENT / UNDETECTABLE ALIGNMENT",
        "reversable": "Y",
        "sphere": "DIVINATION",
        "range": "10YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 TURN",
        "areaOfEffect": "1 CREATURE OR OBJECT",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "SPEAK WITH ANIMALS",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 ANIMAL /W 30FT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "DUST DEVIL",
        "sphere": "ELEMENTAL AIR",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "2RDS",
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "CREATES 1 DUST DEVIL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "FIRE TRAP",
        "costOfComponents": "HOLLY BERRIES",
        "sphere": "ELEMENTAL FIRE",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "PERMANENT UNTIL DISCHARGED",
        "areaOfEffect": "OBJECT TOUCHED",
        "savingsThrow": 0.5
    },
    {
        "spellLevel": 2,
        "spellName": "FLAME BLADE",
        "costOfComponents": "HS & A LEAF FROM A SUMAC",
        "sphere": "ELEMENTAL FIRE",
        "range": 0,
        "components": "VSM",
        "castingTime": 4,
        "duration": "4RDS + 1RD / 2 LEVEL",
        "areaOfEffect": "3FT LONG BLADE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "HEAT METAL / CHILL METAL",
        "reversable": "Y",
        "sphere": "ELEMENTAL FIRE",
        "range": "40YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "7RDS",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 2,
        "spellName": "PRODUCE FLAME",
        "sphere": "ELEMENTAL FIRE",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "SILENCE 15' RADIUS",
        "sphere": "GUARDIAN",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "15FT RADIUS SPHERE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "WYVERN WATCH",
        "costOfComponents": "HS",
        "sphere": "GUARDIAN",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": 5,
        "duration": "8HRS OR UNTIL STRIKE",
        "areaOfEffect": "5FT RADIUS SPHERE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "SLOW POISON",
        "costOfComponents": "HS & A BUD OF GARLIC",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 1,
        "duration": "1HR / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "ENTHRALL",
        "sphere": "LAW",
        "range": 0,
        "components": "VS",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "90FT RADIUS",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "HOLD PERSON",
        "costOfComponents": "A SM STRAIGHT PC OF IRON",
        "sphere": "LAW",
        "range": "120 YDS",
        "components": "VSM",
        "castingTime": 5,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 TO 4 PERSONS IN A 20' CUBE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "AID",
        "costOfComponents": "HS & A STRIP OF WHITE CLOTH /W STICKY SUBSTANCE",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 5,
        "duration": "1RD + 1RD/LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "BARKSKIN",
        "costOfComponents": "HS & A HANDFUL OF BARK FROM AN OAK TREE",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 5,
        "duration": "4RDS + 1RD / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "GOODBERRY / BADBERRY",
        "reversable": "Y",
        "costOfComponents": "HS & SOME EDIBLE BERRIES",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 DAY + 1 DAY / LEVEL",
        "areaOfEffect": "2D4 FRESH BERRIES",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "TRIP",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 5,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "1 OBJECT UP TO 10' LONG",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "WARP WOOD / STRAIGHTEN WOOD",
        "reversable": "Y",
        "sphere": "PLANT",
        "range": "10YDS / LEVEL",
        "components": "VS",
        "castingTime": 5,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 2,
        "spellName": "RESIST FIRE/ RESIST COLD",
        "costOfComponents": "A DROP OF MERCURY",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 5,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "WITHDRAW",
        "sphere": "PROTECTION",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "SPECIAL",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "DUST DEVIL",
        "sphere": "SUMMONING",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "2RDS",
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "CREATES 1 DUST DEVIL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 2,
        "spellName": "MESSENGER",
        "sphere": "SUMMONING",
        "range": "20YDS / LEVEL",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 2,
        "spellName": "OBSCUREMENT",
        "sphere": "WEATHER",
        "range": 0,
        "components": "VS",
        "castingTime": 5,
        "duration": "4RDS / LEVEL",
        "areaOfEffect": "CLOUD, 10FT / LEVEL SQ X 10FT HIGH",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "DISPEL MAGIC",
        "sphere": "ALL",
        "range": "60YDS",
        "components": "VS",
        "castingTime": 6,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "30FT CUBE OR 1 ITEM",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "REMOVE CURSE / BESTOW CURSE",
        "reversable": "Y",
        "sphere": "ALL",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 6,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "HOLD ANIMAL",
        "sphere": "ANIMAL",
        "range": "80YDS",
        "components": "VS",
        "castingTime": 6,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 TO 4 ANIMALS IN A 40' CUBE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 3,
        "spellName": "SUMMONS INSECTS",
        "costOfComponents": "HS, A FLOWER PETAL AND A BIT OF MUD OR CLAY",
        "sphere": "ANIMAL",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "PRAYER",
        "costOfComponents": "A SILVER HS",
        "sphere": "COMBAT",
        "range": 0,
        "components": "VSM",
        "castingTime": 6,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "60FT RADIUS GLOBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "CONTINUAL LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "CREATION",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 6,
        "duration": "PERMANENT",
        "areaOfEffect": "60FT RADIUS GLOBE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "CREATE FOOD & WATER",
        "sphere": "CREATION",
        "range": "10YDS",
        "components": "VS",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "1CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "LOCATE OBJECT / OBSCURE OBJECT",
        "reversable": "Y",
        "costOfComponents": "A PC OF LODESTONE",
        "sphere": "DIVINATION",
        "range": "60YDS + 10YDS/LEVEL",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "1 OBJECT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "SPEAK WITH DEAD",
        "costOfComponents": "HS AND BURNING INSENCE",
        "sphere": "DIVINATION",
        "range": "1YD",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "MELD INTO STONE",
        "costOfComponents": "HS",
        "sphere": "ELEMENTAL EARTH",
        "range": 0,
        "components": "VSM",
        "castingTime": 6,
        "duration": "8RDS + 1D8RDS",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "STONE SHAPE",
        "costOfComponents": "SOFT CLAY",
        "sphere": "ELEMENTAL EARTH",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "3FT CUBE + 1 CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "FLAME WALK",
        "costOfComponents": "HS, AND AT LEAST 500GP OF POWDERED RUBY PER AFFECTED CREATURE",
        "sphere": "ELEMENTAL FIRE",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 5,
        "duration": "1RD + 1RD/LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "PROTECTION FROM FIRE",
        "costOfComponents": "HS",
        "sphere": "ELEMENTAL FIRE",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 6,
        "duration": "SPECIAL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "PYROTECHNICS",
        "costOfComponents": "A FIRE SOURCE",
        "sphere": "ELEMENTAL FIRE",
        "range": "160YDS",
        "components": "VSM",
        "castingTime": 6,
        "duration": "SPECIAL",
        "areaOfEffect": "10 TO 100 X SINGLE FIRE SOURCE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "WATER BREATHING / AIR BREATHING",
        "reversable": "Y",
        "sphere": "ELEMENTAL WATER",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 6,
        "duration": "1HR / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "WATER WALK",
        "costOfComponents": "HS AND A PC OF CORK",
        "sphere": "ELEMENTAL WATER",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 6,
        "duration": "1 TURN + 1 TURN / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "CONTINUAL LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "GUARDIAN",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 6,
        "duration": "PERMANENT",
        "areaOfEffect": "60FT RADIUS GLOBE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "GLYPH OF WARDING",
        "costOfComponents": "DIAMOND DUST WORTH AT LEAST 2,000GPS",
        "sphere": "GUARDIAN",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "SPECIAL",
        "duration": "UNTIL DISCHARGED",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "CURE BLINDNESS OR DEAFNESS / CAUSE",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "CURE DISEASE / CAUSE DISEASE",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "ANIMATE DEAD",
        "costOfComponents": "A DROP OF BLOOD, FLESH OF THE TYPE TO BE ANIMATED & A BONE SHARD OR POWDER",
        "sphere": "NECROMANTIC",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "FEIGN DEATH",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 1,
        "duration": "1 TURN + 1RD / LEVEL",
        "areaOfEffect": "PERSON TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "REMOVE PARALYSIS",
        "sphere": "NECROMANTIC",
        "range": "10YDS / LEVEL",
        "components": "VS",
        "castingTime": 6,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1 TO 4 CREATURES IN A 20FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "SPEAK WITH DEAD",
        "costOfComponents": "HS AND BURNING INSENCE",
        "sphere": "NECROMANTIC",
        "range": "1YD",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "PLANT GROWTH",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "160YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "SNARE",
        "costOfComponents": "A PC OF SINEW, A SNAKE SKIN AND A HS",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "3RDS",
        "duration": "UNTIL TRIGGERED",
        "areaOfEffect": "2FT DIAMETER + 2\" / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "SPIKE GROWTH",
        "costOfComponents": "HS AND SEVEN SHARP THORNS OR TWIGS",
        "sphere": "PLANT",
        "range": "60YDS",
        "components": "VSM",
        "castingTime": 6,
        "duration": "3D4 TURNS +1 / LEVEL",
        "areaOfEffect": "10FT SQ / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "TREE",
        "costOfComponents": "HS AND A TWIG FR A TREE",
        "sphere": "PLANT",
        "range": 0,
        "components": "VSM",
        "castingTime": 6,
        "duration": "1HR + 1 TURN / LEVEL",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "MAGICAL VESTMENT",
        "costOfComponents": "THE VESTMENT TO BE ENCHANTED AND A HS",
        "sphere": "PROTECTION",
        "range": 0,
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "5RDS / LEVEL",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "REMOVE PARALYSIS",
        "sphere": "PROTECTION",
        "range": "10YDS / LEVEL",
        "components": "VS",
        "castingTime": 6,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1 TO 4 CREATURES IN A 20FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "CONTINUAL LIGHT / DARKNESS",
        "reversable": "Y",
        "sphere": "SUN",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 6,
        "duration": "PERMANENT",
        "areaOfEffect": "60FT RADIUS GLOBE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 3,
        "spellName": "STARSHINE",
        "costOfComponents": "SEVERAL STALKS FR AN AMARYLLIS PLANT AND SEVERAL HOLLY BERRIES",
        "sphere": "SUN",
        "range": "10YDS / LEVEL",
        "components": "VSM",
        "castingTime": 6,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "10FTSQ / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 3,
        "spellName": "CALL LIGHTNING",
        "sphere": "WEATHER",
        "range": "360YDS",
        "components": "VS",
        "castingTime": "1 TURN",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "10FT RADIUS",
        "savingsThrow": 0.5
    },
    {
        "spellLevel": 4,
        "spellName": "TONGUES / BABBLE",
        "reversable": "Y",
        "sphere": "ALL",
        "range": 0,
        "components": "VS",
        "castingTime": 7,
        "duration": "1 TURN",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "ANIMAL SUMMONING I",
        "sphere": "ANIMAL",
        "range": "1 MILE RADIUS",
        "components": "VS",
        "castingTime": 7,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "CALL WOODLAND BEINGS",
        "costOfComponents": "A PINE CONE AND A 8 HOLLY BERRIES",
        "sphere": "ANIMAL",
        "range": "100YDS / LEVEL",
        "components": "VSM",
        "castingTime": "SPECIAL",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 4,
        "spellName": "GIANT INSECT",
        "reversable": "Y",
        "costOfComponents": "HS",
        "sphere": "ANIMAL",
        "range": "20YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1 TO 6 INSECTS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "REPEL INSECTS",
        "costOfComponents": "ANY OF THE FOLLOWING CRUSHED MARIGOLD, LEEK, NETTLE LEAVES OR CAMPHOR RESIN",
        "sphere": "ANIMAL",
        "range": 0,
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "10FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "CLOAK OF BRAVERY",
        "reversable": "Y",
        "costOfComponents": "FEATHER OF EAGLE OR HAWK / CHICKEN OR VULTURE",
        "sphere": "CHARM",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 6,
        "duration": "SPECIAL",
        "areaOfEffect": "1 TO 4 CREATURES TOUCHED",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 4,
        "spellName": "FREE ACTION",
        "costOfComponents": "A LEATHER THONG",
        "sphere": "CHARM",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "IMBUE WITH SPELL ABILITY",
        "costOfComponents": "HS + SOME MINOR ITEM SYMBOLIC OF RECIPIENTS PROFESSION",
        "sphere": "CHARM",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "UNTIL USED",
        "areaOfEffect": "PERSON TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "STICKS TO SNAKES",
        "reversable": "Y",
        "costOfComponents": "SM PC OF BARK & SEVERAL SNAKE SCALES",
        "sphere": "CREATION",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1D4 STICKS + 1 STICK / LEVEL IN 10FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "DETECT LIE / UNDETECTABLE LIE",
        "reversable": "Y",
        "costOfComponents": "1GP WORTH OF GOLD DUST / BRASS DUST",
        "sphere": "DIVINATION",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 4,
        "spellName": "DIVINATION",
        "costOfComponents": "HS, INCENSE AND A SACRIFICIAL OFFERING",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "TONGUES / BABBLE",
        "reversable": "Y",
        "sphere": "DIVINATION",
        "range": 0,
        "components": "VS",
        "castingTime": 7,
        "duration": "1 TURN",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "PRODUCE FIRE / QUENCH FIRE",
        "reversable": "Y",
        "costOfComponents": "A PASTE MADE OF SULFUR & WAX FORMED INTO A BALL",
        "sphere": "ELEMENTAL FIRE",
        "range": "40YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1RD",
        "areaOfEffect": "12SQFT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "LOWER WATER / RAISE WATER",
        "reversable": "Y",
        "costOfComponents": "HS AND A PINCH OF DUST",
        "sphere": "ELEMENTAL WATER",
        "range": "120YDS",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "REFLECTING POOL",
        "costOfComponents": "OIL EXTRACTED FROM WALNUT & HICKORY 3OZS",
        "sphere": "ELEMENTAL WATER",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "2HRS",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "ABJURE",
        "costOfComponents": "HS, HW AND SOME MATERIAL INIMICAL TO THE CREATURE",
        "sphere": "GUARDIAN",
        "range": "10FT",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 4,
        "spellName": "CURE SERIOUS WOUNDS / CAUSE",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 7,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "NEUTRALIZE POISON / POISON",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 7,
        "duration": "PERMANENT",
        "areaOfEffect": "CREATURE TOUCHED OR 1CUFT / 2 LEVELS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "NEUTRALIZE POISON / POISON",
        "reversable": "Y",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 7,
        "duration": "PERMANENT",
        "areaOfEffect": "CREATURE TOUCHED OR 1CUFT / 2 LEVELS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "HALLUCINATORY FOREST",
        "sphere": "PLANT",
        "range": "80YDS",
        "components": "VS",
        "castingTime": 7,
        "duration": "PERMANENT",
        "areaOfEffect": "40SQFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "HOLD PLANT",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "80YDS",
        "components": "VS",
        "castingTime": 7,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 4,
        "spellName": "PLANT DOOR",
        "costOfComponents": "HS AND A PC OF CHARCOAL",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 7,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "SPEAK WITH PLANTS",
        "costOfComponents": "A DROP OF WATER, A PINCH OF DUNG AND A FLAME",
        "sphere": "PLANT",
        "range": 0,
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "30FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "STICKS TO SNAKES",
        "reversable": "Y",
        "costOfComponents": "SM PC OF BARK & SEVERAL SNAKE SCALES",
        "sphere": "PLANT",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "1D4 STICKS + 1 STICK / LEVEL IN 10FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "PROTECTION FROM EVIL / GOOD , 10' RADIUS",
        "reversable": "Y",
        "costOfComponents": "HW AND BURNING INCENSE / UHW AND SMOLDERING DUNG",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "10FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "SPELL IMMUNITY",
        "costOfComponents": "SAME COMPONENTS OF THE SPELL BEING PROTECTED AGAINST",
        "sphere": "PROTECTION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "ABJURE",
        "costOfComponents": "HS, HW AND SOME MATERIAL INIMICAL TO THE CREATURE",
        "sphere": "SUMMONING",
        "range": "10FT",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 4,
        "spellName": "CONTROL TEMPERTURE, 10' RADIUS",
        "costOfComponents": "A STRIP OF WILLOW BARK AND RASBERRY LEAVES",
        "sphere": "WEATHER",
        "range": 0,
        "components": "VSM",
        "castingTime": 7,
        "duration": "4 TURNS + 1 TURN / LEVEL",
        "areaOfEffect": "10FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 4,
        "spellName": "PROTECTION FROM LIGHTNING",
        "costOfComponents": "HS",
        "sphere": "WEATHER",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "ATONEMENT",
        "costOfComponents": "HS, PRAYER BEADS, WHEEL OR BOOK & BURNING INCENSE",
        "sphere": "ALL",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "PERSON TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "COMMUNE",
        "costOfComponents": "HS, HW AND INCENSE",
        "sphere": "ALL",
        "range": 0,
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "QUEST",
        "costOfComponents": "HS",
        "sphere": "ALL",
        "range": "60YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "UNTIL FULFILLED",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 5,
        "spellName": "TRUE SEEING / FALSE SEEING",
        "reversable": "Y",
        "costOfComponents": "AN OINTMENT THAT COSTS 300GPS PRODUCTION IS TIME CONSUMING & SPECIAL",
        "sphere": "ALL",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 8,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "ANIMAL GROWTH / SHRINK ANIMAL",
        "reversable": "Y",
        "costOfComponents": "HS AND A SCRAP OF FOOD",
        "sphere": "ANIMAL",
        "range": "80YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "UP TO 8 ANIMALS IN A 20FT CUBE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "ANIMAL SUMMONING II",
        "sphere": "ANIMAL",
        "range": "60 YDS / LEVEL",
        "components": "VS",
        "castingTime": 8,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "COMMUNE WITH NATURE",
        "sphere": "ANIMAL",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "3RD",
        "duration": "UNTIL TRIGGERED",
        "areaOfEffect": "2' DIAMETER + 2\" LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "INSECT PLAGUE",
        "costOfComponents": "A FEW GRAINS OF SUGAR, GRAIN & A SMEAR OF FAT",
        "sphere": "ANIMAL",
        "range": "120YDS",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "180' DIAMETER X 60' HIGH CLOUD",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "PLANESHIFT",
        "costOfComponents": "A SMALL FORKED METAL ROD",
        "sphere": "ASTRAL",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 8,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED (SPECIAL)",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 5,
        "spellName": "FLAME STRIKE",
        "costOfComponents": "A PINCH OF SULFUR",
        "sphere": "COMBAT",
        "range": "60YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "5' RADIUS X 30' HIGH COLUMN",
        "savingsThrow": 0.5
    },
    {
        "spellLevel": 5,
        "spellName": "MAGIC FONT",
        "costOfComponents": "HS + THE TYPE OF FONT TO BE MAGICKED",
        "sphere": "DIVINATION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 HR",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "CONTROL WINDS",
        "sphere": "ELEMENTAL AIR",
        "range": 0,
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "30' RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "SPIKE STONES",
        "costOfComponents": "FOUR TINY STALACTITES",
        "sphere": "ELEMENTAL EARTH",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": 6,
        "duration": "3D4 TURNS +1 TURN / LEVEL",
        "areaOfEffect": "10SQFT / LEVEL, 1 SPIKE / SQFT",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "TRANSMUTE ROCK TO MUD / MUD TO ROCK",
        "reversable": "Y",
        "costOfComponents": "CLAY & WATER / SAND, LIME AND WATER",
        "sphere": "ELEMENTAL EARTH",
        "range": "160YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "SPECIAL",
        "areaOfEffect": "20CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "WALL OF FIRE",
        "costOfComponents": "A PINCH OF PHOSPHORUS",
        "sphere": "ELEMENTAL FIRE",
        "range": "80YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "TRANSMUTE ROCK TO MUD / MUD TO ROCK",
        "reversable": "Y",
        "costOfComponents": "CLAY & WATER / SAND, LIME AND WATER",
        "sphere": "ELEMENTAL WATER",
        "range": "160YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "SPECIAL",
        "areaOfEffect": "20CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "DISPEL EVIL",
        "costOfComponents": "HS & HW / HS & UHW",
        "sphere": "GUARDIAN",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 8,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 5,
        "spellName": "CURE / CAUSE CRITICAL WOUNDS",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 8,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "AIR WALK",
        "costOfComponents": "HS AND A BIT OF THISTLEDOWN",
        "sphere": "LAW",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 8,
        "duration": "1HR + 1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "RAISE DEAD / SLAY LIVING",
        "reversable": "Y",
        "sphere": "NECROMANTIC",
        "range": "30YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1 PERSON",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 5,
        "spellName": "ANTI-PLANT SHELL",
        "sphere": "PLANT",
        "range": 0,
        "components": "VS",
        "castingTime": 8,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "15FT DIAMETER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "COMMUNE WITH NATURE",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "3RD",
        "duration": "UNTIL TRIGGERED",
        "areaOfEffect": "2' DIAMETER + 2\" LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "PASS PLANT",
        "costOfComponents": "A SPRIG OF MISTLETOE",
        "sphere": "PLANT",
        "range": "SPECIAL",
        "components": "VSM",
        "castingTime": 8,
        "duration": "1 USE (1RD / LEVEL MAX)",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "ANTI-PLANT SHELL",
        "sphere": "PROTECTION",
        "range": 0,
        "components": "VS",
        "castingTime": 8,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "15FT DIAMETER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "DISPEL EVIL",
        "costOfComponents": "HS & HW / HS & UHW",
        "sphere": "SUMMONING",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 8,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NEGATES"
    },
    {
        "spellLevel": 5,
        "spellName": "MOONBEAM",
        "costOfComponents": "A PC OF OPALESCENT FELDSPAR & SEVERAL SEEDS FR A MOONSEED PLANT",
        "sphere": "SUN",
        "range": "60YDS + 10YDS/LEVEL",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "5FT RADIUS + SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "RAINBOW",
        "costOfComponents": "HS & HW OR A DIAMOND WITH BLESS & PRAYER CAST ON IT VALUE 1,000GPS",
        "sphere": "SUN",
        "range": "120YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 5,
        "spellName": "CONTROL WINDS",
        "sphere": "WEATHER",
        "range": "120YDS",
        "components": "VS",
        "castingTime": 4,
        "duration": "1HR + 1HRTURN/LEVEL",
        "areaOfEffect": "20' RADIUS GLOBE",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 5,
        "spellName": "RAINBOW",
        "costOfComponents": "HS & HW OR A DIAMOND WITH BLESS & PRAYER CAST ON IT VALUE 1,000GPS",
        "sphere": "WEATHER",
        "range": "120YDS",
        "components": "VSM",
        "castingTime": 7,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "SPEAK WITH MONSTERS",
        "sphere": "ALL",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "THE CASTER",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "ANIMAL SUMMONING III",
        "sphere": "ANIMAL",
        "range": "100 YDS / LEVEL",
        "components": "VS",
        "castingTime": 9,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "ANTI-ANIMAL SHELL",
        "costOfComponents": "HS & A HANDFUL OF PEPPER",
        "sphere": "ANIMAL",
        "range": 0,
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "20FT DIAMETER SPHERE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "WORD OF RECALL",
        "sphere": "COMBAT",
        "range": 0,
        "components": "V",
        "castingTime": 1,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "ANIMATE OBJECT",
        "sphere": "CREATION",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "1CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "BLADE BARRIER",
        "sphere": "CREATION",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "3RDS / LEVEL",
        "areaOfEffect": "5 TO 60SQFT",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 6,
        "spellName": "HEROES FEAST",
        "costOfComponents": "HS & FERMENTED HONEY",
        "sphere": "CREATION",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1HR",
        "areaOfEffect": "1 INDIVIDUAL / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "FIND THE PATH",
        "costOfComponents": "A SET OF DIVINATION COUNTERS, BONES, STICKS, CARVED RUNES, ETC",
        "sphere": "DIVINATION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "3RDS",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "STONE TELL",
        "costOfComponents": "A DROP OF MERCURY & A BIT OF CLAY",
        "sphere": "DIVINATION",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1 TURN",
        "areaOfEffect": "1 CUYD",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "AERIAL SERVANT",
        "sphere": "ELEMENTAL AIR",
        "range": "10YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "FIRE SEEDS",
        "costOfComponents": "ACORNS OR HOLLY BERRIES",
        "sphere": "ELEMENTAL FIRE",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD / SEED",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": 1
    },
    {
        "spellLevel": 6,
        "spellName": "PART WATER",
        "costOfComponents": "HS",
        "sphere": "ELEMENTAL WATER",
        "range": "20YDS / LEVEL",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "TRANSMUTE WATER TO DUST",
        "reversable": "Y",
        "costOfComponents": "DIAMOND DUST WORTH AT LEAST 500GPS, A BIT OF SEASHELL & HS",
        "sphere": "ELEMENTAL WATER",
        "range": "60YDS",
        "components": "VSM",
        "castingTime": 8,
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1CUYD / LEVEL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 6,
        "spellName": "BLADE BARRIER",
        "sphere": "GUARDIAN",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "3RDS / LEVEL",
        "areaOfEffect": "5 TO 60SQFT",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 6,
        "spellName": "FORBIDDANCE",
        "costOfComponents": "HS AND HW & INCENSE WORTH 1000GPS IF PASSWORD INCENSE WORTH 5000GPS PER 60FT CUBE",
        "sphere": "GUARDIAN",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": "6RDS",
        "duration": "PERMANENT",
        "areaOfEffect": "60CUFT / LEVEL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 6,
        "spellName": "HEAL",
        "reversable": "Y",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "LIVEOAK",
        "costOfComponents": "HS",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "1 OAK TREE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "TRANSPORT VIA PLANTS",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": 4,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "TURN WOOD",
        "sphere": "PLANT",
        "range": 0,
        "components": "VS",
        "castingTime": 9,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "120FT WIDE X 20FT LONG / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "WALL OF THORNS",
        "sphere": "PLANT",
        "range": "80YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "10CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "ANTI-ANIMAL SHELL",
        "costOfComponents": "HS & A HANDFUL OF PEPPER",
        "sphere": "PROTECTION",
        "range": 0,
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1 TURN / LEVEL",
        "areaOfEffect": "20FT DIAMETER SPHERE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "AERIAL SERVANT",
        "sphere": "SUMMONING",
        "range": "10YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "1 DAY / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "ANIMATE OBJECT",
        "sphere": "SUMMONING",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "1RD / LEVEL",
        "areaOfEffect": "1CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "CONJURE ANIMALS",
        "sphere": "SUMMONING",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 9,
        "duration": "2RDS / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "WORD OF RECALL",
        "sphere": "SUMMONING",
        "range": 0,
        "components": "V",
        "castingTime": 1,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 6,
        "spellName": "FORBIDDANCE",
        "costOfComponents": "HS AND HW & INCENSE WORTH 1000GPS IF PASSWORD INCENSE WORTH 5000GPS PER 60FT CUBE",
        "sphere": "WARDS",
        "range": "30YDS",
        "components": "VSM",
        "castingTime": "6RDS",
        "duration": "PERMANENT",
        "areaOfEffect": "60CUFT / LEVEL",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 6,
        "spellName": "WEATHER SUMMONING",
        "sphere": "WEATHER",
        "range": 0,
        "components": "VS",
        "castingTime": "1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "GATE",
        "sphere": "ALL",
        "range": "30YDS",
        "components": "VS",
        "castingTime": 5,
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "CREEPING DOOM",
        "sphere": "ANIMAL",
        "range": 0,
        "components": "VS",
        "castingTime": "1RD",
        "duration": "4RDS / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "REINCARNATE",
        "sphere": "ANIMAL",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1 TURN",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "PERSON TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "ASTRAL SPELL",
        "sphere": "ASTRAL",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "1/2 HR",
        "duration": "SPECIAL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "CONFUSION",
        "costOfComponents": "A SET OF 3 NUT SHELLS",
        "sphere": "CHARM",
        "range": "80YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "40CUFT",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 7,
        "spellName": "EXACTION",
        "costOfComponents": "HS, SOME MATTER FR CREATURE'S PLANE OF EXSISTENCE AND WRITTEN KNOWLEDGE ON PARCHMENT",
        "sphere": "CHARM",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "HOLY WORD / UNHOLY WORD",
        "reversable": "Y",
        "sphere": "COMBAT",
        "range": 0,
        "components": "V",
        "castingTime": 1,
        "duration": "SPECIAL",
        "areaOfEffect": "30FT RADIUS",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "WIND WALK",
        "costOfComponents": "FIRE & PURE WATER",
        "sphere": "ELEMENTAL AIR",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1HR / LEVEL",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "ANIMATE ROCK",
        "costOfComponents": "A STONE AND A DROP OF BLOOD FR THE CASTER",
        "sphere": "ELEMENTAL EARTH",
        "range": "40YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "1RD / LEVEL",
        "areaOfEffect": "2CUFT / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "EARTHQUAKE",
        "costOfComponents": "A PINCH OF DIRT, A PC OF ROCK & A LUMP OF CLAY",
        "sphere": "ELEMENTAL EARTH",
        "range": "120YDS",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "1RD",
        "areaOfEffect": "5FT DIAMETER / LEVEL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "TRANSMUTE METAL TO WOOD",
        "sphere": "ELEMENTAL EARTH",
        "range": "80YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "1 METAL OBJECT",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 7,
        "spellName": "CHARIOT OF SUSTARRE",
        "costOfComponents": "A SM PC OF WOOD, 2 HOLLY BERRIES & A FIRE SOURCE AS LEAST AS BRIGHT AS A TORCH",
        "sphere": "ELEMENTAL FIRE",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "12HRS",
        "areaOfEffect": "SPECIAL",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "FIRE STORM / FIRE QUENCH",
        "reversable": "Y",
        "sphere": "ELEMENTAL FIRE",
        "range": "160YDS",
        "components": "VS",
        "castingTime": "1RD",
        "duration": "1RD",
        "areaOfEffect": "20CUFT / LEVEL",
        "savingsThrow": 0.5
    },
    {
        "spellLevel": 7,
        "spellName": "SYMBOL",
        "sphere": "GUARDIAN",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "3 OR 1 TURN",
        "duration": "SPECIAL",
        "areaOfEffect": "60FT RADIUS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 7,
        "spellName": "REGENERATE / WITHER",
        "reversable": "Y",
        "costOfComponents": "HS & HW / HS & UHW",
        "sphere": "HEALING",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "3RDS",
        "duration": "SPECIAL",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "RESTORATION / ENERGY DRAIN",
        "reversable": "Y",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VS",
        "castingTime": "3RDS",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "RESURRECTION / DESTRUCTION",
        "reversable": "Y",
        "costOfComponents": "HS & HW / HS & UHW",
        "sphere": "NECROMANTIC",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "INSTANTANEOUS",
        "areaOfEffect": "CREATURE TOUCHED",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "CHANGESTAFF",
        "costOfComponents": "HS & STAFF OR LEAVES FR THE SAME SORT OF STAFF",
        "sphere": "PLANT",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": 4,
        "duration": "SPECIAL",
        "areaOfEffect": "THE CASTER'S STAFF",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "EXACTION",
        "costOfComponents": "HS, SOME MATTER FR CREATURE'S PLANE OF EXSISTENCE AND WRITTEN KNOWLEDGE ON PARCHMENT",
        "sphere": "SUMMONING",
        "range": "10YDS",
        "components": "VSM",
        "castingTime": "1RD",
        "duration": "SPECIAL",
        "areaOfEffect": "1 CREATURE",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "SUCCOR / SUMMON PRIEST",
        "reversable": "Y",
        "costOfComponents": "THE COST IS BETWEEN 2,000 & 5,000 GPS",
        "sphere": "SUMMONING",
        "range": "TOUCH",
        "components": "VSM",
        "castingTime": "1 DAY",
        "duration": "SPECIAL",
        "areaOfEffect": "CREATES 1 ITEM",
        "savingsThrow": "NONE"
    },
    {
        "spellLevel": 7,
        "spellName": "SUNRAY",
        "costOfComponents": "A ASTER SEED & A PC OF SUNSTONE",
        "sphere": "SUN",
        "range": "10YDS / LEVEL",
        "components": "VSM",
        "castingTime": 4,
        "duration": "1RD + 1D4RDS",
        "areaOfEffect": "5FT RADIUS",
        "savingsThrow": "SPECIAL"
    },
    {
        "spellLevel": 7,
        "spellName": "CONTROL WEATHER",
        "costOfComponents": "HS, INCENSE AND PRAYER BEADS OR SIMILAR ITEM",
        "sphere": "WEATHER",
        "range": 0,
        "components": "VSM",
        "castingTime": "1 TURN",
        "duration": "4D12 HOURS",
        "areaOfEffect": "4D4 SQ MILES",
        "savingsThrow": "NONE"
    }
]

export default priestSpells;